[workspace]
release = true

[[package]]
name = "readmesh-core"
publish = false

[[package]]
name = "readmesh-store"
publish = false

[[package]]
name = "readmesh-plugin"
publish = false

[[package]]
name = "readmesh-net"
publish = false

[[package]]
name = "readmesh-transport"
publish = false

[[package]]
name = "readmesh-metalink"
publish = false

[[package]]
name = "readmesh-sync"
publish = false

[[package]]
name = "readmesh-daemon"
publish = false

[[package]]
name = "readmesh-rpc"
publish = false

[[package]]
name = "readmesh-app"
publish = false

[[package]]
name = "readmesh-cli"
publish = false

[[package]]
name = "readmesh-ui"
publish = false
