#[derive(Clone, PartialEq)]
pub struct Theme {
    pub bg_app: &'static str,
    pub bg_surface: &'static str,
    pub bg_surface_2: &'static str,
    pub bg_container: &'static str,
    pub bg_highlight: &'static str,
    pub text_primary: &'static str,
    pub text_secondary: &'static str,
    pub text_dim: &'static str,
    pub text_on_accent: &'static str,
    pub accent: &'static str,
    pub accent_dim: &'static str,
    pub accent_soft: &'static str,
    pub ok: &'static str,
    pub err: &'static str,
    pub border: &'static str,
    pub reader_bg: &'static str,
    pub reader_text: &'static str,
    pub font_size_sm: &'static str,
    pub font_size_base: &'static str,
    pub font_size_lg: &'static str,
    pub font_size_xl: &'static str,
    pub font_size_2xl: &'static str,
    pub font_size_3xl: &'static str,
    pub space_1: i32,
    pub space_2: i32,
    pub space_3: i32,
    pub space_4: i32,
    pub space_5: i32,
    pub radius_sm: &'static str,
    pub radius_md: &'static str,
    pub radius_lg: &'static str,
    pub radius_full: &'static str,
}

impl Theme {
    pub fn dark() -> Self {
        Self {
            bg_app: "#0f1319",
            bg_surface: "#171d26",
            bg_surface_2: "#1e2632",
            bg_container: "#1e263280",
            bg_highlight: "#e8a33d1a",
            text_primary: "#e8ecf1",
            text_secondary: "#c8d0dc",
            text_dim: "#96a1b0",
            text_on_accent: "#0f1319",
            accent: "#e8a33d",
            accent_dim: "#9a6b24",
            accent_soft: "#e8a33d33",
            ok: "#4caf7d",
            err: "#e05d5d",
            border: "#2a3442",
            reader_bg: "#12161c",
            reader_text: "#d8dee6",
            font_size_sm: "11px",
            font_size_base: "14px",
            font_size_lg: "16px",
            font_size_xl: "18px",
            font_size_2xl: "24px",
            font_size_3xl: "32px",
            space_1: 4,
            space_2: 8,
            space_3: 16,
            space_4: 24,
            space_5: 32,
            radius_sm: "4px",
            radius_md: "8px",
            radius_lg: "12px",
            radius_full: "9999px",
        }
    }
}
