[package]
name = "ln-metalink"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
blake3.workspace = true

# XML parsing
quick-xml = { version = "0.37", features = ["serialize"] }

[dev-dependencies]
serde_json.workspace = true
