[package]
name = "readmesh-ui-dioxus"
version = "0.1.0"
edition = "2024"

[features]
default = ["desktop"]
desktop = ["dep:dioxus-desktop", "dioxus/desktop", "dioxus/lib", "dioxus/launch"]
web = ["dioxus/web", "dioxus/lib", "dioxus/launch", "dep:web-sys"]

[dependencies]
readmesh-core.workspace = true
readmesh-app.workspace = true
serde.workspace = true
tracing.workspace = true
blake3.workspace = true

dioxus = { version = "0.7", default-features = false }
dioxus-desktop = { version = "0.7", optional = true }

# workaround: dioxus-web@0.7.9 is missing Location feature on web-sys
web-sys = { version = "0.3", features = ["Location"], optional = true }
